### ISSUE TITLE
RSS Link

### ISSUE THREAD

**Issue by orbitalmartian8** [orbitalmartian8/orbitalblog#3]
Make a proper button for the RSS link.

_Originally posted by @orbitalmartian8 in https://github.com/orbitalmartian8/newblog/issues/2#issuecomment-1658989720_

**Comment by Illuminati9** [comment]
Hello @orbitalmartian8 , I want to work on this issue, Can you please explain this issue in detail? :)

**Comment by orbitalmartian8** [comment]
> Hello @orbitalmartian8 , I want to work on this issue, Can you please explain this issue in detail? :)

Hey @Illuminati9 , thanks for the interest, to provide more details, I want a nicer looking button than the default html button. If you want, I can assign this issue to you. :)

**Comment by Illuminati9** [comment]
Hey @orbitalmartian8 , i want to work on this issue. Can you please assign me this issue :)

**Comment by orbitalmartian8** [comment]
@Illuminati9 Awesome, of course I can assign you :)
